services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-omarelbaz}:${POSTGRES_PASSWORD}@db:5432/neodocs"
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
      KAFKA_BROKERS: "kafka:29092"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    ports:
      - "3001:3001"
    restart: unless-stopped

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-omarelbaz}:${POSTGRES_PASSWORD}@db:5432/neodocs"
      KAFKA_BROKERS: "kafka:29092"
      NODE_ENV: production
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      VITE_API_URL: ${API_URL:-http://localhost:3001}
    ports:
      - "80:80"
    restart: unless-stopped
